proxy:
  image: jwilder/nginx-proxy:latest
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
db:
  image: mysql:5.7.7
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: mypass
  ports:
    - "3306:3306"
dbdata:
  image: mysql:5.7.7
  command: /bin/echo mysql Data container
redis:
  image: redis
cache:
  image: memcached
web:
  build: .
  command: bundle exec unicorn -E production -c config/unicorn.rb
  environment:
    SECRET_KEY_BASE: abcdefg
    VIRTUAL_HOST: beer.docker
    RAILS_ENV: production
  links:
    - db
    - redis
    - cache
worker:
  build: .
  command: bundle exec sidekiq -e production -c 25
  environment:
    SECRET_KEY_BASE: abcdefg
    RAILS_ENV: production
  links:
    - db
    - redis
    - cache
